export ZSH=/home/osiris/.oh-my-zsh
export ZSH_THEME="powerlevel9k/powerlevel9k"
export HYPHEN_INSENSITIVE="true"
export ENABLE_CORRECTION="true"
export COMPLETION_WAITING_DOTS="true"
export HIST_STAMPS="yyyy-mm-dd"
export plugins=(sudo)

export PATH="${PATH}:/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/home/osiris/bin:/home/osiris/bin/td:/home/osiris/bin/wlantest:/home/osiris/bin/mount-usb-drive:/home/osiris/.gem/ruby/2.3.0/bin:/home/osiris/bin/burp-suite"

source $ZSH/oh-my-zsh.sh

export LANG=en_US.UTF-8

export ARCHFLAGS="-arch x86_64"

export BROWSER="/usr/bin/qutebrowser"
export VISUAL="vim"
export EDITOR="vim"
export PAGER="vimpager"
export CC="/usr/bin/clang"
export GOPATH="${HOME}/repos/go"
export ICU_DATA="/usr/local/share/icudt58l.dat"

